apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-tls
spec:
  secretName: api-rsm-prod-ca-secret
  issuerRef:
    name: api-rsm-prod-clusterissuer
    kind: ClusterIssuer
  commonName: kibana.rsm-prod-cloud.vodafone.local
  dnsNames:
    - kibana.rsm-prod-cloud.vodafone.local