apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: kube-apps
  sources:
    # Chart from Chart Repo
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 55.7.0
      helm:
        valueFiles:
        - $values/kubernetes-apps/prometheus/values.yaml
    # Values from Git
    - repoURL: 'https://github.com/umitkarabudak-ICW/devops'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true