apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.haproxy.service.name }}
spec:
  type: {{ .Values.haproxy.service.type }}
  ports:
    {{- toYaml .Values.haproxy.service.ports | nindent 10 }}
  selector:
    app: {{ .Values.haproxy.appName }}



