apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
    app.kubernetes.io/component: {{ .Values.service.name }}
    app.kubernetes.io/instance: {{ .Values.service.name }}
spec:
  clusterIP: None
  ports:
    {{- toYaml .Values.service.ports | nindent 10 }}
  selector:
    app: {{ .Values.appName }}



