##################################################
# ElasticSearch Service
##################################################  
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: ClusterIP
  ports:
  - name: rest
    port: 9200
  - name: inter-node
    port: 9300