kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  redis-slave.conf: |
    slaveof redis.stock.svc.cluster.local 6379
    protected-mode no
    requirepass {{ .Values.password }}
    masterauth {{ .Values.password }}
    port 6379
    notify-keyspace-events KEA
  redis.conf: |
    protected-mode no
    requirepass {{ .Values.password }}
    masterauth {{ .Values.password }}
    port 6379
    notify-keyspace-events KEA