kind: Secret
apiVersion: v1
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    template: redis-persistent-template
  annotations:
    template.openshift.io/expose-password: '{.data[''database-password'']}'
data:
  database-password: MXZDT0s0WGREOQ==
type: Opaque
