apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    name: {{ include "redis.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 10 }}
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
    name: {{ include "redis.fullname" . }}
