apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  labels:
    name: redis-slave
spec:
  replicas: 3 
  selector:
    matchLabels:
      name: redis-slave
  template:
    metadata:
      labels:
        name: redis-slave
    spec:
      subdomain: slave
      volumes:
        - name: conf
          configMap: 
            name: redis-slave-conf
      containers:
      - name: redis
        image: redis:6.2.5
        env:
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        command:
          - "redis-server"
        args:
          - "/conf/redis.conf"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: conf
          mountPath: /conf