apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis-slave
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    name: redis
    port: 6379
    targetPort: 6379 
  selector:
    app: redis-slave
