apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: rsm
spec:
  kafka:
    version: 3.6.0
    replicas: 6
    resources:
      requests:
        memory: 256Mi
        cpu: "300m"
      limits:
        memory: 368Mi
        cpu: "300m"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: true
        configuration:
          bootstrap:
            annotations:
              advertisedHost: kafka-bootstrap.rsm-prod-cloud.vodafone.local
              advertisedPort: 443
           #nodePort: 32200
          brokers:
          - broker: 0
            advertisedHost: kafka-broker0.rsm-prod-cloud.vodafone.local
            advertisedPort: 443
            #nodePort: 32003
          - broker: 1
            advertisedHost: kafka-broker1.rsm-prod-cloud.vodafone.local
            advertisedPort: 443
            #nodePort: 32004
          - broker: 2
            advertisedHost: kafka-broker2.rsm-prod-cloud.vodafone.local
            advertisedPort: 443
          - broker: 3
            advertisedHost: kafka-broker3.rsm-prod-cloud.vodafone.local
            advertisedPort: 443
          - broker: 4
            advertisedHost: kafka-broker4.rsm-prod-cloud.vodafone.local
            advertisedPort: 443
          - broker: 5
            advertisedHost: kafka-broker5.rsm-prod-cloud.vodafone.local
            advertisedPort: 443
            #nodePort: 32005
          brokerCertChainAndKey:
            secretName: api-rsm-prod-ca-secret
            certificate: tls.crt
            key: tls.key
    config:
      offsets.topic.replication.factor: 6
      transaction.state.log.replication.factor: 6
      transaction.state.log.min.isr: 4
      default.replication.factor: 6
      min.insync.replicas: 4
      inter.broker.protocol.version: "3.6"
      ssl.cipher.suites: TLS_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 # (1)
      ssl.enabled.protocols: TLSv1.3, TLSv1.2 # (2)
      ssl.protocol: TLSv1.3 # (3)
      ssl.endpoint.identification.algorithm: HTTPS
    producer.config:
      max.block.ms: 60000
    consumer.config:
      max.poll.interval.ms: 300000
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
  zookeeper:
    replicas: 6
    storage:
      type: ephemeral
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: "300m"
        limits:
          memory: 368Mi
          cpu: "300m"
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
    userOperator: {}