apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis-master
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  ports:
  - protocol: TCP
    name: redis
    port: 6379
    targetPort: 6379 
  selector:
    app: redis-master
